create table
  public.pa_survey (
    id uuid not null default gen_random_uuid (),
    prolific_pid text null,
    response1 smallint null,
    response2 smallint null,
    response3 smallint null,
    response4 smallint null,
    response5 smallint null,
    response6 smallint null,
    response7 smallint null,
    response10 smallint null,
    response11 smallint null,
    response12 smallint null,
    response13 smallint null,
    response14 smallint null,
    response15 smallint null,
    response16 smallint null,
    response17 smallint null,
    response18 smallint null,
    response19 smallint null,
    task1 text null,
    task1_org_prompt text null,
    task1_user_prompt text null,
    task1_pa_prompt text null,
    task2 text null,
    task2_org_prompt text null,
    task2_user_prompt text null,
    task2_pa_prompt text null,
    task3 text null,
    task3_org_prompt text null,
    task3_user_prompt text null,
    task3_pa_prompt text null,
    task4 text null,
    task4_user_prompt text null,
    task5 text null,
    task5_user_prompt text null,
    task6 text null,
    task6_user_prompt text null,
    prestudy_timestamp timestamp without time zone null,
    task1_timestamp timestamp without time zone null,
    task2_timestamp timestamp without time zone null,
    task3_timestamp timestamp without time zone null,
    task4_timestamp timestamp without time zone null,
    task5_timestamp timestamp without time zone null,
    task6_timestamp timestamp without time zone null,
    poststudy_timestamp timestamp without time zone null,
    start_timestamp timestamp without time zone null,
    task smallint null,
    age text null,
    gender text null,
    use text null,
    job text null,
    demographic_timestamp timestamp without time zone null,
    constraint pa_survey_pkey primary key (id)
  ) tablespace pg_default;
